### ISSUE TITLE
Add Test Contract address to foundry.toml Reference

### ISSUE THREAD

**Issue by nnnnicholas** [onbjerg/foundry-book#43]
Test contracts are deployed to `0xb4c79dab8f259c7aee6e5b2aa729821864227e84`, but this address is not listed in the [`config.md` reference](https://github.com/onbjerg/foundry-book/blob/master/src/reference/config.md). 

A quick test confirms this is the deploy address.

```solidity
//SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.0 <0.9.0;

import "ds-test/test.sol";

contract JustChecking is DSTest{
    function testDeployer() public {
        emit log_named_address("msg.sender", msg.sender);
        emit log_named_address("tx.origin", tx.origin);
        emit log_named_address("this", address(this));
    }
}
```

Output
```
Logs:
  msg.sender: 0x00a329c0648769a73afac7f9381e08fb43dbea72
  tx.origin: 0x00a329c0648769a73afac7f9381e08fb43dbea72
  this: 0xb4c79dab8f259c7aee6e5b2aa729821864227e84
```

I do not know if there is an environment variable in Forge to control the test deploy address. In DS-Test this environment variable is called `DAPP_TEST_ADDRESS` ([see here](https://github.com/dapphub/dapptools/blob/e9d454af4953b1f61c7f3fcfad595601c3e14521/src/hevm/README.md)).

It is useful to have this address somewhere in the documentation because this contract is the default owner of contracts deployed by the test.
